AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: My Spring Boot Application

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.spring.bancospring.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
            Path: /{proxy+}
            Method: ANY
  MyBucket:
    Type: AWS::S3::Bucket

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          TargetOriginId: MyBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: MyBucketOrigin
            DomainName: !GetAtt MyBucket.DomainName
            S3OriginConfig: { }
Metadata:
  BuildMethod: docker
