
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      #      porta que o zookeeper está no container, no caso o kafka usa essa porta
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      #     para qualquer cliente no nosso host, eles precisam usar a porta 22181
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:latest
    container_name: db-cliente
    #    reinicia o container quando a máquina é reiniciada
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "teste1234"
    ports:
      - "3306:3306"
    #   Mantém os dados do Mysql persistente mesmo após recriar ou excluir o container
    volumes:
      #   Define um volume de dados chamado 'dbdata' (precisa ter o ./ antes),
      # anexado ao container do mysql e montado no diretório '/var/lib/mysql' (diretório
      # padrão usado pelo mysql para armazenar todos os arquivos de dados)
      - ./dbdata:/var/lib/docker/volumes/todo-mysql-data

  postgres:
    image: postgres:latest
    container_name: db-conta

    #    reinicia o container quando a máquina é reiniciada
    restart: always
    environment:
      POSTGRES_user: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    #   Mantém os dados do Mysql persistente mesmo após recriar ou excluir o container

    volumes:
      #   Define um volume de dados chamado 'dbdata' (precisa ter o ./ antes),
      # anexado ao container do mysql e montado no diretório '/var/lib/mysql' (diretório
      # padrão usado pelo mysql para armazenar todos os arquivos de dados)
      - ./dbdata:/var/lib/postgresql/data





